name: 'Terraform Plan'

on:
  push:
    branches:
      - stage

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
 
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ap-northeast-1

    # terraformのバージョンを指定
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.5

    - name: Terraform Init
      run: terraform init
      working-directory: terraform
 
    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform