name: 'Terraform Plan'

on:
  push:
    branches: [ "stage" ]
  pull_request:
    branches: [ "stage" ]

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
 
    steps:
    - name: set ROLE
      run: |
        echo "AWS_ROLE_ARN=$" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v4

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ap-northeast-1

    # .terraform-versionファイルからterraformのバージョンを取得
    - name: Get Terraform version
      id: terraform-version
      uses: bigwheel/get-terraform-version-action@v1.2.0
      with:
        path: ${{ inputs.working-directory }}

    # terraformのバージョンを指定
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ steps.terraform-version.outputs.terraform-version }}

    - name: Terraform Init
      run: terraform init
      working-directory: terraform
 
    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform