name: 'Terraform Plan'

on:
  pull_request:
    branches: 
      - main

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ap-northeast-1

    # .terraform-versionファイルからterraformのバージョンを取得
    - name: Get Terraform version
      id: terraform-version
      uses: bigwheel/get-terraform-version-action@v1.2.0
      with:
        path: ${{ inputs.working-directory }}

    # terraformのバージョンを指定
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ steps.terraform-version.outputs.terraform-version }}

    - name: init
      run: terraform init

    - name: plan
      run: terraform plan